### ISSUE TITLE
multiple arguments not working

### ISSUE THREAD

**Issue by hypery11** [VR-25/djs#1]
here is my djs.conf
```
versionCode=201906290
boot /data/local/tmp/atx-agent server -d
```
in this case, not working, how can i fix?
⚙⚙⚙⚙⚙

**Comment by VR-25** [comment]
Does `atx-agent`have execute permissions?

You may want to try `boot source...` or `boot sh...`.
  e.g., _boot . /data/local/tmp/atx-agent server -d_
