### ISSUE TITLE
boot rules not working after update 202108091

### ISSUE THREAD

**Issue by rhayy** [VR-25/djs#12]
Here is my `config.txt`:

```
versionCode=201908180
boot setenforce 1
```

It used to work with version _201910180_.

Even adding this line:
`1235 touch /mnt/sdcard/Download/touch.txt; : --delete`
it makes no effect; it even remains in the config file when it should have been deleted.

However, I can edit the config file with the command line.

I tried to uninstall and install it again but that does not make it work.

I am using Magisk.

I don't know how to debug this.

**Comment by VR-25** [comment]
Is djs daemon actually running?
`djs,` should print a process ID.

**Comment by rhayy** [comment]
It is:
```
pollux:/ # djs,
1386
pollux:/ #
```
For more information, the device (sony xperia tablet Z) is on lineage 16.0.

**Comment by rhayy** [comment]
That does work when I set a time like:
```
1131 setenforce 1; : --delete
```

But it doesn't work on boot:
```
boot setenforce 1
boot touch /data/I-was-born-on-boot; : --delete
```

The file has NOT been created but the rule has been deleted.

**Comment by VR-25** [comment]
What if it's too early to run those commands - i.e., due to unavailability and data encryption?
```
boot while [ ! -d /sdcard/Android ]; do sleep 10; done; setenforce 1
boot while [ ! -d /sdcard/Android ]; do sleep 10; done; touch /data/I-was-born-on-boot; : --delete
```
Try those.

**Comment by rhayy** [comment]
I tried them with no effect.

It works well until release [202108020](https://github.com/VR-25/djs/releases/tag/v2021.8.2). Since the next one ([202108091](https://github.com/VR-25/djs/releases/tag/v2021.8.9.1)), no more.

So, I looked at the code and what has been changed between these two releases is `djs.sh` especially.

I investigated more and I found the bug in this [line](https://github.com/VR-25/djs/blob/9a8d2c2182dffacab2ee1e8fa3fab7ca9943a4eb/djs/djs.sh#L80): `grep '^boot | : --boot' $config | sed 's/^.... //' >> $tmpDir/boot.sh`
where `|` is not interpreted corredtly.
It should be `egrep `or [`grep -E`].

**Comment by VR-25** [comment]
Fixed, thanks!
