### ISSUE TITLE
DJS does not run on a system with no /sbin directory

### ISSUE THREAD

**Issue by lefth** [VR-25/djs#6]
I'm running the xiaomi.eu ROM (Android 11) on a Xiaomi Poco F2 Pro device. When I install DJS as a Magisk module, the operation completes without error. However, after rebooting there is no `djs` command. Having read some of the scripts, I can see the the software is trying to modify /sbin, which doesn't exist. The command to create `/sbin` fails. Would it be possible to initialize using another directory? I am using other root software such as ACC and AccA successfully.

[init.log](https://github.com/VR-25/djs/files/5338431/init.log)

I see that /sbin is hard coded in some places, but other parts of the scripts will check the existence of different paths, such as the logic that sets `$installDir` in `install.sh`. I gather this is because some pieces of data are assumed to always reside in /sbin, while others are more flexible. Is there anything I can do to help test or debug this?

**Comment by Gronkdalonka** [comment]
I cobbled up a quick and dirty workaround where i adapted all the sbin paths.
Works on my crdroid 7.3 (Android 11)

Pull request is up https://github.com/VR-25/djs/pull/9
