### ISSUE TITLE
DJS not working on Android 11

### ISSUE THREAD

**Issue by peppelongo96** [VR-25/djs#8]
I recently update my phone to Android 11 and commands line don't work too. The module can't be recognized by the system as it doesn't seem installed

**Comment by takobaba** [comment]
Same issue here.

I have tried with online install and magisk install methods on 2 different ROMs on A11.

Doesnt work.

A11 seems to install it under `/data/adb/djs` and when its run:
`    
    127|dipper:/sdcard # /data/adb/djs/djsd-start.sh`
`
    /data/adb/djs/djsd-start.sh[2]: /sbin/.djs/djs/djsd.sh: inaccessible or not found`
`
    dipper:/sdcard # /data/adb/djs/djsc.sh`
`
    /data/adb/djs/djsc.sh[21]: .: /sbin/.djs/djs/busybox.sh: No such file or directory`
